# Jekyll Site Generator Settings

url: http://www.wxwidgets.org
permalink: /news/:year/:month/:title/
lsi: false
pygments: true
markdown: rdiscount

exclude:
  - Gruntfile.js
  - node_modules
  - package.json
  - README.md
  - Vagrantfile

# Custom Settings

disqus_shortname: wxwidgets